name: CI
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [ "main", "stable" ]
  pull_request:
    branches: [ "main", "stable" ]

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5.3.0
        with:
          go-version: 1.23.6

      - name: Test all packages in the module
        run: go test ./...
      
      - name: Run go fmt and check for changes
        run: |
          # Run go fmt in write mode to apply formatting
          go fmt ./...

          # Check if there are any changes
          if git diff --exit-code; then
            echo "No formatting issues detected."
          else
            echo "Formatting issues detected. Please run 'go fmt' locally."
            exit 1
          fi
      
