name: CI
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [ "main", "stable", "cdLs" ]
  pull_request:
    branches: [ "main", "stable" ]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: 1.23.6

      - name: Run Tests
        run: go test ./...

      - name: Run go fmt and check for changes
        run: |
          go fmt ./...
          git diff --exit-code || (echo "Formatting issues detected. Please run 'go fmt' locally." && exit 1)
